* Slideshow
** Image Database
Images tagged in exif or anything [[https://drewnoakes.com/code/exif/][metadata extractor]] can read with
creation date. Images are access mainly by date.  Important access:
- by current date in different year,
- by current month in different years
Scanning of the database could take place once a day or something For
fast startup database can be cached in a yaml file but the real source
is just a filesystem.

** Installation
Put the service and path file from src/systemd to
~/.config/systemd/user enable and start the slideshow.service and
slideshow-watcher.path units.

** Hardware
*** RaspberryPi
*** Motion Sensor
https://www.amazon.de/gp/product/B00Q6OJ8AC
https://www.hackster.io/hardikrathod/pir-motion-sensor-with-raspberry-pi-415c04
xset dpms force off xset dpms force on
https://www.amazon.de/Pyroelectrische-Infrarot-Bewegung-Sensor-Detektor/dp/B008AESDSY

*** GPIOs
**** Java
Pi4J // https://mvnrepository.com/artifact/com.pi4j/pi4j-core compile
group: 'com.pi4j', name: 'pi4j-core', version: '1.2'


*** 
The system should lookout if the hdmi connection is active, and only
be active if hdmi is on. [[https://stackoverflow.com/questions/5813195/detecting-if-the-monitor-is-powered-off][ddcontrol]] might help here. Unfortunatly it
does not. It seems there is no way to learn, that a display connected
via hdmi is indeed on or tuned to the hdmi connection.

*** Photos.app
*** Example
https://gist.github.com/bartonp/867f5187935d88a903395b6833a6fdf8

**** Favorites
sqlite3 tmp/photos.db "select imagePath from RKVersion inner join
RKMaster where RKVersion.isFavorite = 1 and RKMaster.uuid =
RKVersion.masterUuid;"

**** List all albums
sqlite3 tmp/photos.db "select modelId,name from RKAlbum where
RKAlbum.albumSubclass==3 and RKAlbum.isInTrash==0;"

**** List images in album
sqlite3 tmp/photos.db "select RKMaster.modelId,RKMaster.imagePath from
RKMaster,RKVersion,RKAlbumVersion where RKAlbumVersion.albumId==58780
and RKAlbumVersion.versionId==RKVersion.modelId and
RKVersion.masterId==RKMaster.modelId and RKMaster.isInTrash==0;"

**** Orientation
is stored in the RKVersion table in the orientation column 1 - no
rotation 8 - rotate to left 3 - rotate twice to left 6 - rotate 3
times to left


*** Reverse geocoding
https://nominatim.org/release-docs/develop/api/Reverse/

*** Colors
https://www.schemecolor.com/watermelon.php
https://www.schemecolor.com/avocado.php

*** Weather
New onecall api, has everything, windspeed, uvindex, ...  Example:
http
"https://api.openweathermap.org/data/2.5/onecall?lat=48.0878521&lon=11.5414829&appid=9d8617eb77cba019774d79121d412a0e&units=metric"

BUT it does not have proper min/max values for the current day, only
for the rest of the starting from the current time.  Historical data
is available (https://openweathermap.org/api/one-call-api#history),
but only from -5d .. -6h.  So we record the min max of the current day
and collect it over time (in the night, we get the best values for the
rest of the day).

**** icons
https://github.com/manifestinteractive/weather-underground-icons
my-weather-indicator

** Import from Photos database
select count (*) from zgenericasset where zgenericasset.ZFAVORITE=1;
pragma table_info(zgenericasset);
